### ISSUE TITLE
Meteor Todo Example Rework

### ISSUE THREAD

**Issue by ncrmro** [TheHackerSociety/hpd#1]
http://hpdconnect.meteor.com/lists/JQjRydXjn2xRYDL55

Rework of the the Meteor Todo's example, URL's need to be added as well as removing the ability to edit the lists and todo's. I'll probably put of refactoring the names list and todo's ATM and safe that for building out testing. The list is hardcoded in the /server/boostrap.js file, not sure if we still want user accounts maybe for newsletters but it's already built in?

Mobile version and iOS apps work still setting up the android environment.

Let me know if you'd like the pull on a development branch?

**Comment by JohnGoodman** [comment]
nice. are you going to the mega hack night tonight? we can run through it then if so.

**Comment by ncrmro** [comment]
Yep see you there, should have some more done before then.

**Comment by ncrmro** [comment]
Ok changed the input text to working click through urls, still needs to remove some of the user facing edit items. I'm not sure if we need to have an admin account that can edit stuff. I have everything hardcoded to seed the db if nothing is found eg reset db every change atm.
